[project]
name = "ps4debug"
version = "1.0.0"
description = "Asynchronous ps4debug implementation in Python."
keywords = ["ps4", "ps4debug", "homebrew", "debug", "debugging", "reverse-engineering"]
authors = [
  {name = "Jay184", email = "me@jay0.mozmail.com"},
]
maintainers = [
  {name = "Jay184", email = "me@jay0.mozmail.com"},
]
license = "0BSD"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autoregistry>=1.2.1",
    "construct>=2.10.70",
    "construct-typing>=0.7.0",
    "pydantic>=2.12.5",
    "pydantic-construct>=0.1.1",
]

[project.urls]
Repository = "https://github.com/Jay184/PyPS4debug.git"
Issues = "https://github.com/Jay184/PyPS4debug/issues"

[dependency-groups]
dev = [
    "coverage>=7.13.5",
    "invoke>=2.2.1",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-randomly>=4.0.1",
    "hypothesis>=6.151.10",
    "ruff>=0.15.8",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.coverage.run]
omit = [
    "tests/*"
]

[tool.coverage.report]
exclude_also = [
    "raise AssertionError",
    "raise NotImplementedError",
]

[tool.ruff]
exclude = [
    ".venv",
    "tests",
]
